Re-wrote to TypeScript, added webpack hot-loader, added prettier, re-wrote FNR and KID
Tripletex/YesCommons pull request #29
Opened 2021-07-06 08:10 UTC by torland-klev

I started re-writing to TS, but some of the code was a bit buggy and hard to read/maintain, so I re-wrote it 😅😁 
I've tested the new code towards the previous code and other online resources, but automatic testing is further necessary.

2021-07-16 08:17 UTC, tanettrimas requested changes
Mye bra endringer her, en liten ting som muligens må endres ettersom jeg ser at det riktig sjekkes for bindestrek i koden som kaller mod11-funksjonen. Men da må mod11 også concatenere det i resultatet for at det skal gi verdi, ikke kalle seg selv på nytt.

2021-07-16 08:17 UTC, tanettrimas commented on src/lib/mod/mod11.ts
> +  if (step5 === '-')
Man skal egentlig concate bindestreken på resultatet, også skal kalleren av funksjonen bestemme om funksjonen skal trigges på nytt. For eksempel så er et fødselsnummer som blir generert med bindestrek ugyldig - mens et kid-nummer kan være gyldig selv med bindestrek

2021-07-16 08:35 UTC, tanettrimas commented on package.json
>      "node-fetch": "^2.6.1",
Her må det legges til typescript som en devdependency, hvis ikke fungerer ikke start:dev scriptet ditt. Kan være greit å ha det uansett slik at man ikke er avhengig av å ha det globalt installert.

2021-07-25 13:29 UTC, tanettrimas commented
If you merge this branch into the PR branch, the merge conflicts should be resolved: https://github.com/Tripletex/YesCommons/tree/torland-klev-rewrite-to-typescript

2021-08-02 15:29 UTC, torland-klev commented
Merge conflicts fixed

2021-08-04 08:30 UTC, tanettrimas approved these changes
Very nice, LGTM :)

2021-08-04 08:31 UTC, merged